on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  pull-requests: read
name: SonarCloud Analysis
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=arvincs
            -Dsonar.projectKey=ArvinCS_eshop-tutorial
